apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dnaas-deploy
spec:
  replicas: 6
  template:
    metadata:
      labels:
        run: dnaas
    spec:
      containers:
      - name: dnaas
        image: mattva01/dnaas:0.4.2
        ports:
          - containerPort: 8080
        env:
          - name: KUBE_NODE_NAME
            valueFrom: 
               fieldRef:
                  fieldPath: spec.nodeName
          - name: MOJO_REDIS_URL
            value: "redis://dnaas-redis-master:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: dnaas
  labels:
    run: dnaas
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: dnaas
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dnaas-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: k8s-primary-ingress
spec:
  rules:
  - host: dnaas.hyperninja.net
    http:
      paths:
        - backend:
            serviceName: dnaas
            servicePort: http
---
